config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  resources :reservations, only: [:new, :create] do
    member do
      post 'change_status'
    end
  end

  get "/my_gardes", to: "gardes#view_my_gardes", as: "my_gardes"
  get "/my_garde/:id", to: "gardes#view_my_garde", as: "my_garde"
  get "/my_reservations", to: "reservations#view_my_reservations", as: "my_reservations"


  resources :gardes do

    resources :garde_categories, only: [:new, :create]

  end

    # resources :meal_categories, only: [:new, :create]
    # resources :meal_ingredients, only: [:new, :create]
    # resources :reviews, only: [ :new, :create ]



    # resources :reviews, only: [ :new, :create ]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :garde_categories
  has_many :gardes, through: :garde_categories
end

app/models/garde.rb
class Garde < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_many :clients_users, through: :reservations, source: :user
  has_many :garde_categories, dependent: :destroy
  has_many :categories, through: :garde_categories
  # has_many :reviews




  CATEGORIES = ["Garde d'enfant", "Courses", "Aide aux devoirs", "Aide aux personnes âgées"]

  # pg_search_scope :global_search,
  #   against: [ :name, :description, :category ],
  #   associated_against: {
  #     user: [ :username]
  #   },
  #   using: {
  #     tsearch: { prefix: true }
  #   }


  validates :name, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :contact, presence: true

  # validates :quantity_max, presence: true, numericality: { only_integer: true }
  # validates :start_availability_date, presence: true
  # validates :end_availability_date, presence: true
  # mount_uploader :photo, PhotoUploader


  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  # def can_delete?
  #   !self.reservations.pluck(:status).include?('accepted')
  # end

  # def left_quantity
  #   if !can_delete?
  #     self.quantity_max - self.reservations.where(status: "accepted").pluck(:reservation_quantity).reduce(:+)
  #   else
  #     self.quantity_max
  #   end
  # end

  # def rating_average
  #   self.reviews.map { |review| review.rating }.reduce(:+) / self.reviews.count.to_f
  # end
end

app/models/garde_category.rb
class GardeCategory < ApplicationRecord
  belongs_to :garde
  belongs_to :category
  validates :garde, presence: true
  validates :category, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :garde

  validates :reservation_quantity, presence: true, numericality: { only_integer: true }
  validates :pick_up_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :gardes, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :booked_reservations, through: :reservations, source: :gardes

  # validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/garde_categories_controller.rb
class GardeCategoriesController < ApplicationController
  before_action :set_garde, only: [:new, :create]
  def new
    @garde_category = GardeCategory.new
  end

  def create
  end

  private

  def garde_category_params
    params.require(:garde_category).permit(:garde_id)
  end

  def set_garde
    @garde = Garde.find(params[:garde_id])
  end
end

app/controllers/gardes_controller.rb
class GardesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_garde, only: [:show, :edit, :update, :destroy]


  def index
    @gardes = Garde.geocoded


    @markers = @gardes.map do |garde|
      {
        lat: garde.latitude,
        lng: garde.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { garde: garde })

      }
    end
  end


  def show
    @garde = Garde.find(params[:id])
    @reservation = Reservation.new
  end

  def view_my_gardes
    @my_gardes = Garde.where(user: current_user)

    my_received_gardes = []

    @my_gardes.each do |garde|
      my_received_gardes << garde.reservations
    end

    @my_received_gardes = my_received_gardes.flatten
  end

  def view_my_garde
    @my_gardes = Garde.where(user: current_user)
    @my_garde = @my_gardes.find(params[:id])
  end

  def new
    @garde = Garde.new
  end

  def create
    @garde = Garde.new(garde_params)
    @garde.user = current_user
    if @garde.save
      redirect_to garde_path(@garde)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @garde.update(garde_params)
    redirect_to garde_path(@garde)
  end

  def destroy
    @garde.destroy
    redirect_to my_gardes_path
  end

  private

  def set_garde
    @garde = Garde.find(params[:id])
  end

  def garde_params
    params.require(:garde).permit(:name, :description, :contact, :category, :address, :quantity_max, :start_availability_date, :end_availability_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservation = Reservation.all
  end

  def view_my_reservations
    @my_reservations = Reservation.where(user: current_user)
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user
    @garde = Garde.find(params[:garde_id])
    @reservation.garde = @garde
    if @reservation.save
      flash[:notice] = "Votre réservation a bien été enregistrée"
      redirect_to my_reservations_path
    else
      render 'gardes/show'
    end
  end


  def change_status
    @reservation = Reservation.find(params[:id])
    params[:status] == "accept" ? @reservation.status = 'accepted' : @reservation.status = 'declined'
    @reservation.save
    redirect_to my_gardes_path
  end

  private

  def reservation_params
    params.require(:reservation).permit(:reservation_quantity, :pick_up_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/garde_categories/_new.html.erb
  <%= simple_form_for [@garde, @garde_category] do |f| %>
    <%= f.association :category, collection: Category::CATEGORY %>
    <%= render "meal_categories/precisions_form" %>
  <% end %>

app/views/garde_categories/_precisions_form_for.html.erb
    <%= simple_form_for [@garde, @garde_category] do |f| %>
      <%= f.association :category, include_blank: false %>
      <%= f.submit "add it", class: "btn btn-dark" %>
    <% end %>
    </div>
  </div>

app/views/gardes/_form.html.erb
<%= simple_form_for(@garde) do |f| %>
  <%= f.input :name, label: 'Mon service' %>
  <%= f.input :description, label: 'Description'  %>

  <%= f.input :address, label: 'Mon adresse' %>

  <%= f.input :quantity_max, label: 'Nombre de personnes maximum (en cas de garde)' %>
  <%= f.input :contact, label: 'Mon numéro de téléphone ou mail' %>
  <%= f.input :start_availability_date, label: 'date de début', as: :string, required: false, input_html: {class: "datepicker"} %>
  <%= f.input :end_availability_date, label: 'date de fin', as: :string, required: false, input_html: {class: "datepicker"} %>


  <%= f.submit "Ok, je propose mon aide", class: "cool-bouton-big"  %>
  <% end %>

app/views/gardes/_info_window.html.erb
<h2><%= garde.name %></h2>

<p><%= garde.address %></p>
<button class="button map-link">
  <%= link_to "Selectionner", garde_path(garde) %>
</button>

app/views/gardes/edit.html.erb
<div class="form-meals">
  <h2> Editer votre service </h2>
  <%= render 'form', garde: @garde %>
</div>

app/views/gardes/index.html.erb
<!-- mosaic of meals -->
<div class="cards_and_map_container">
  <div class="intro">
    <div class="mot">Bienvenu sur CoronAides, la plateforme de "solidarité Coronavirus" du groupe Nice-Matin.
    </div>
    <div class="expli">
      Le principe? Garde d'enfants, faire des courses pour des personnes âgées, échanges de produits de première nécessité, un peu de réconfort... Vous pouvez proposer tous types d'aides à vos voisins ou habitants de votre quartier. <b>Pour proposer vos services, rendez-vous dans l'onglet "Proposer un service".</b>
    </div>
    <div class="expli">
      Notre plateforme ne vous permet pas de réserver une garde d'enfants ou une livraison de courses à domicile. Il s'agit UNIQUEMENT d'un outil de recensement des bonnes volontés sur notre territoire. C'est à vous de prendre contact par mail ou le cas échéant au téléphone avec les personnes ayant proposé leurs services.
    </div>
  </div>

    <% @gardes.each do |garde| %>
      <!-- <div class="box col-6"> -->

      <div class="garde-card">

        <div class="meal-card-content">
            <div class="meal-card-title">
              <div class="garde-name"><%= garde.name %></div>
            </div>
            <div class="garde-details"><%= garde.address %></div>
            <div class="garde-details"><%= garde.start_availability_date %></div>


                <div class="garde-details">Proposé par: <%= garde.user.username %></div>


            </div>
        <button class="bouton-ok">

          <%= link_to "+", garde_path(garde) %>
        </button>
      </div>
    <% end %>

  <div id="map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/gardes/new.html.erb
<div class="container-formulaire">
  <div class="formu-container">
    <h2> Je propose </h2>
    <div class="cool-bouton">
    <%= link_to "Retour", gardes_path %>
    </div>
  </div>
  <div class="form-meals">
    <%= render 'form', garde: @garde %>
  </div>
</div>

app/views/gardes/show.html.erb
 <div class="reservation-container">

          <h1><%= @garde.name.capitalize %></h1>


      <div class="garde-info-details">
        <% if @garde.user == current_user %>
          <p>Proposé par: Moi</p>
          <% else %>
          <p>Proposé par <%= @garde.user.username %> </p>
          <% end %>
        <p>Description: <%= @garde.description %> </p>
        <% if @garde.quantity_max != nil %>
        <p> Nombre de personnes max : <%= @garde.quantity_max %> </p>
        <p>Adresse: <%= @garde.address %> </p>
        <p>Contact: <%= @garde.contact %> </p>
        <p>Date: <%= @garde.start_availability_date %> </p>
        <% end %>

      </div>
    <!-- div photo + nom -->
    <div class="reservation">

      <% if @garde.user != current_user %>
        <div class="resa">

            <%= simple_form_for(@reservation) do |f| %>
              <%= hidden_field_tag :garde_id, @garde.id %>
              <%= f.input :pick_up_date, label: 'Choisir une date' %>
              <%= f.submit "Ok, je réserve", class: "cool-bouton" %>
            <% end %>
          <% else %>

        </div>
      <% end %>

    </div>
  </div>
  <div class="choix">
  <% if @garde.user == current_user %>
  <div class="go-back-bouton">
  <%= link_to "Retour aux services", gardes_path %>
  </div>
  <p><%= link_to "Modifier", edit_garde_path(@garde), class:"btn btn-outline-dark" %>
  <% end %>

  </p>
</div>
  <!-- div left content -->
</div>

app/views/gardes/view_my_garde.html.erb
<div class="container py-2">
  <div class="row">
    <div class="col-8">
      <div class="meal_header d-flex justify-content-between py-3 border-bottom">
        <div class="meal_big_titles">
          <h1><%= @garde.name.capitalize %></h1>

        </div>
        <div class="user_pic_and_name d-flex flex-column align-items-center">
          <img src="https://resize-parismatch.lanmedia.fr/img/var/news/storage/images/paris-match/people-a-z/javier-bardem/6033180-8-fre-FR/Javier-Bardem.jpg" alt="" class="">
          <p><%= @garde.user.username %></p>
        </div>
      </div>
      <div class="meal_text">
        <p><%= @garde.description %></p>
      </div>
    </div>


  <!--   <div class="location">
    </div> -->
  </div>
</div>

app/views/gardes/view_my_gardes.html.erb
<div class="container">



  <h2 class="my-services">Mes services</h2>
      <% @my_gardes.each do |garde| %>
        <div class="card-items" >

          <div class="card-item-infos">
            <p><%= garde.name %></p>
            <p><%= garde.start_availability_date %></p>
            <% if garde.quantity_max != nil %>
            <p>Nombre max :<%=  garde.quantity_max %></p>
            <% end %>
            <p><%= garde.description %></p>


            <div class="choix">
              <p><%= link_to "Edit", edit_garde_path(garde.id), class:"btn btn-outline-dark" %></p>
              <p><%= link_to "Delete", garde_path(garde.id), class:"btn btn-outline-dark",
                method: :delete,
                data: { confirm: "Are you sure?" } %>
             </p>
           </div>


          </div>
        </div>
    <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CoroHelp</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'shared/navbar'  %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>


  </body>
</html>

app/views/pages/home.html.erb
<div class="home-container">



</div>

app/views/reservations/view_my_reservations.html.erb
<div class="resa-container">
  <h1>Mes réservations</h1>
    <% @my_reservations.each do |reservation| %>
      <div class="order-card">


        <div class="my-orders-info-details">
          <div class="my-resa-details">
            <h2><%= reservation.garde.name %></h2>
            <p><%= reservation.garde.description %></p>
            <h5>🗓 Réservé pour le <strong><%= reservation.pick_up_date %></strong></h5>
            <h5>Proposé par <strong><%= reservation.garde.user.username %></strong></h5>




            </div>
          </div>


        </div>
      <% end %>
    </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to root_path do %>
    <img class="logo" src=""/>
  <% end %>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
          <%= link_to "Proposer/Demander un service", new_garde_path, class: "nav-link d-block d-sm-none" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Mes gardes", my_gardes_path, class: "nav-link d-block d-sm-none" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Mes réservations", my_reservations_path, class: "nav-link d-block d-sm-none" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Mon profil", "#", class: "nav-link d-block d-sm-none" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Log out", destroy_user_session_path, class: "nav-link d-block d-sm-none" %>
      </li>

      <button class="border-none add-meal" type="button" >
          <%= link_to "Proposer un service", new_garde_path %>
        </button>



      <li class="dropdown align-self-center d-none d-sm-block mr-3">
        <button class="dropdown-toggle border-none" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Mes infos
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <% if user_signed_in? %>

          <%= link_to "Mes services", my_gardes_path, class: "dropdown-item" %>
          <%= link_to "Mes réservations", my_reservations_path, class: "dropdown-item" %>
          <%= link_to "Mon profil", "#", class: "dropdown-item d-block d-sm-none" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>